# Use postgres/example user/password credentials
version: '3.1'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    
    depends_on:
      - frontend
      - backend

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: urlshortener

    volumes:
      - ./backend/db:/var/lib/postgresqgl/data

  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile

    depends_on:
      - backend

  backend:
    build:
      context: backend/
      dockerfile: Dockerfile

    depends_on:
      - db